chore(rebranding): migrate scripts and docs (#2272)

diff --git a/scripts/gen-protoc-gen-dart b/scripts/gen-protoc-gen-dart
--- a/scripts/gen-protoc-gen-dart
+++ b/scripts/gen-protoc-gen-dart
@@ -19,8 +19,8 @@ save_file="protoc-gen-dart_${kernelname}_amd64"
 
 # Check dir else create save dir
 if [[ $(basename ${setdir}) = "scripts" ]] ; then
-    if [[ $(basename $(dirname "${setdir}")) = "starport" ]] ; then
-        [[ -d $(dirname "${setdir}/pkg/protoc-gen-dart/data") ]] || mkdir -p "$(dirname "${setdir}")/starport/pkg/protoc-gen-dart/data"
+    if [[ $(basename $(dirname "${setdir}")) = "ignite" ]] ; then
+        [[ -d $(dirname "${setdir}/pkg/protoc-gen-dart/data") ]] || mkdir -p "$(dirname "${setdir}")/ignite/pkg/protoc-gen-dart/data"
     else
         echo "Attention: you are running the script out of the startport project please run it this script in: https://github.com/ignite-hq/cli"
         exit 1
@@ -57,5 +57,5 @@ cd - &> /dev/null || exit
 # Compile the file
 
 dart compile exe "${setfile}" --output "${save_file}"
-[[ -f "${save_file}" ]] && mv "${save_file}" "$(dirname ${setdir})/starport/pkg/protoc-gen-dart/data" || { echo "cannot create the binary file!" ; exit 1; }
-echo "the binary moved to '$(dirname "${setdir}")/starport/pkg/protoc-gen-dart/data/${save_file}'"
+[[ -f "${save_file}" ]] && mv "${save_file}" "$(dirname ${setdir})/ignite/pkg/protoc-gen-dart/data" || { echo "cannot create the binary file!" ; exit 1; }
+echo "the binary moved to '$(dirname "${setdir}")/ignite/pkg/protoc-gen-dart/data/${save_file}'"
